### ISSUE TITLE
Run belugas-python feature detector on 10 python projects

### ISSUE THREAD

**Issue by mayra-cabrera** [Gueils/belugas-python#24]
Please list the projects on this issue description

**Comment by walreyes** [comment]
### Django
1. https://github.com/Inboxen/Inboxen - [Files]()
2. https://github.com/getsentry/sentry - [Files]()
3. https://github.com/delneg/noteshrinker-django - [Files]()
4. https://github.com/cidadania/django-file-repository - [Files]()
5. https://github.com/ratancs/learning-django-web-development - [Files]()
6. https://github.com/gitenberg-dev/giten_site - [Files]()
7. https://github.com/thejsj/django-and-rethinkdb - [Files]()
8. https://github.com/manojlds/django-ansible/blob/master/requirements.txt - [Files]()
9. https://github.com/valberg/djangit/blob/master/requirements_base.txt - [Files]()
10. https://github.com/Signbank/NGT-signbank - [Files]()

**Comment by mayra-cabrera** [comment]
@walreyes do you think we can support another web framework?

**Comment by walreyes** [comment]
We could, I have no idea of what python frameworks exist even less how to dockerize them but I can do research.

**Comment by mayra-cabrera** [comment]
Please do. I understand it's a pain in the ass since it involves a research on python web frameworks and try to dockerize a language we're not experts on. If it helps these are the steps we followed for dockerizing PHP repos

1. Research on php frameworks. Basically googling _"top 5 PHP frameworks for 2017"_. Did 3 of those and select the ones that always appear.
2. With the frameworks on "1" search for docker hub images, and build a recipe for the whales-api for those frameworks
3. And that's it

We're not hoping for the perfect Dockerfile or docker-compose.yml just a decent "base" as a starting point :v:

**Comment by walreyes** [comment]
Got it, I'm on it.

**Comment by mayra-cabrera** [comment]
Cool.. I'm closing this :v:
